from fpdf import FPDF
from fpdf.enums import XPos, YPos
import os

def generate_pdf_report(ats_score: dict, skill_gap: dict, filepath: str = "reports/final_report.pdf"):
    """Generates a PDF report containing the ATS score and Skill Gap analysis."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=15, style='B')
    
    # Title
    pdf.cell(w=190, h=10, text="AI Resume Analysis Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.ln(10)
    
    # ATS Score Section
    pdf.set_font("helvetica", size=12, style='B')
    pdf.cell(w=190, h=10, text=f"ATS Score: {ats_score.get('ATS Score', 0)} / 100", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", size=11)
    
    breakdown = ats_score.get("Breakdown", {})
    for key, val in breakdown.items():
        pdf.cell(w=190, h=10, text=f"  - {key}: {val}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
    pdf.ln(5)
    
    # Skill Gap Section
    pdf.set_font("helvetica", size=12, style='B')
    pdf.cell(w=190, h=10, text=f"Skill Match: {skill_gap.get('match_percentage', 0)}%", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font("helvetica", size=11)
    
    matched = ", ".join(skill_gap.get("matched_skills", []))
    missing = ", ".join(skill_gap.get("missing_skills", []))
    
    pdf.multi_cell(w=190, h=10, text=f"Matched Skills: {matched if matched else 'None'}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.multi_cell(w=190, h=10, text=f"Missing Skills: {missing if missing else 'None'}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(10)
    pdf.set_font("helvetica", size=10, style='I')
    pdf.cell(w=190, h=10, text="Generated by AI Resume Analyzer + Interview Coach", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    
    pdf.output(filepath)
    return filepath
